Update `README.md`, add Secrets Instructions, re-encrypt secrets, DRY part of script (#172)
Updates to the README as the result of going through the onboarding process.

* Update `README.md`
* Add secrets instructions
* re-encrypt secrets
* DRY part of secrets script

diff --git a/scripts/secrets_manager b/scripts/secrets_manager
--- a/scripts/secrets_manager
+++ b/scripts/secrets_manager
@@ -1,39 +1,47 @@
 #!/bin/bash
 
 function check_dependencies() {
+  if [[ $1 == "-exit_on_install" ]]; then
+    EXIT_ON_INSTALL="YES"
+  fi
+
   echo '----------------------------'
   echo 'Checking dependencies'
   echo '----------------------------'
 
+  DEPENDENCY_INSTALLED="NO"
   if ! [ -x "$(command -v age)" ]; then
-  	echo 'age is not installed. installing with `brew install age`' >&2
-  	brew install age;
+    echo 'age is not installed. installing with `brew install age`' >&2
+    brew install age;
 
     if ! [ -x "$(command -v age)" ]; then
-  	  echo 'age is still not installed. installing with `brew install age`' >&2
-  	  exit 1
-	  else 
-      echo 'all dependencies installed' 
+      echo 'age is still not installed. installing with `brew install age`' >&2
+      exit 1
+    else
+      DEPENDENCY_INSTALLED="YES"
     fi
-	else 
-    echo 'all dependencies installed' 
-	fi
+  fi
 
-}
+  if ! [ -x "$(command -v rename)" ]; then
+    echo 'rename is not installed. installing with `brew install rename`' >&2
+    brew install rename;
 
-function check_dependencies_silent() {
-  # Only emits messages upon failure & exit
-  if ! [ -x "$(command -v age)" ]; then
-  	brew install age;
-
-    if ! [ -x "$(command -v age)" ]; then
-  	  echo 'age is still not installed. installing with `brew install age`' >&2
-  	  exit 1
-	  else 
-      echo 'dependencies installed, re-run script' 
-      exit
+    if ! [ -x "$(command -v rename)" ]; then
+      echo 'rename is still not installed. installing with `brew install rename`' >&2
+      exit 1
+    else
+      DEPENDENCY_INSTALLED="YES"
     fi
-	fi
+  fi
+
+  if [[ $EXIT_ON_INSTALL == "YES" ]]; then
+    if [[ "$DEPENDENCY_INSTALLED" == "YES" ]]; then 
+      echo 'One or more dependencies installed, re-run the script' >&2
+      exit 1
+    fi
+  fi
+  
+  echo "All dependencies installed"
 }
 
 function project_directory() {
@@ -131,23 +139,23 @@ function generate_and_rename_cocoapodkeys() {
 }
 
 function check_for_contributor_public_keys() {
-    echo '----------------------------'
-    echo 'Checking for valid public keys file'
-    echo '----------------------------'
+  echo '----------------------------'
+  echo 'Checking for valid public keys file'
+  echo '----------------------------'
 
-    project_dir=$(project_directory)
-    contributor_public_keys="$project_dir/secrets/contributor_public_keys"
+  project_dir=$(project_directory)
+  contributor_public_keys="$project_dir/secrets/contributor_public_keys"
 
-    if [ -s "$contributor_public_keys" ]; then
-      # The file is not-empty.
-      echo '----------------------------'
-      echo "$(wc -l < "$contributor_public_keys") Public keys found"
-      echo '----------------------------'
-    else
-      # The file is empty.
-      echo '----------------------------'
-      echo 'Public keys file not found, or empty, run `generate_and_save_contributor_keys`'
-      echo '----------------------------'
-      exit 1;
-    fi
+  if [ -s "$contributor_public_keys" ]; then
+    # The file is not-empty.
+    echo '----------------------------'
+    echo "$(wc -l < "$contributor_public_keys") Public keys found"
+    echo '----------------------------'
+  else
+    # The file is empty.
+    echo '----------------------------'
+    echo 'Public keys file not found, or empty, run `generate_and_save_contributor_keys`'
+    echo '----------------------------'
+    exit 1;
+  fi
 }
