WIP checkin of functions and convenience scripts todo the secrets management

diff --git a/scripts/secrets_manager b/scripts/secrets_manager
--- a/scripts/secrets_manager
+++ b/scripts/secrets_manager
@@ -65,3 +65,76 @@ function check_for_existing_keys() {
   fi
 }
 
+function decrypt_secrets() {
+  security find-generic-password -a swift-repo-user -s swift-repo-private > /dev/null 2>&1
+
+  script_path=$(readlink -f "${BASH_SOURCE}")
+  script_dir=$(dirname "$script_path")
+  project_dir=$(dirname "$script_dir")
+  keys_encrypted="$project_dir/secrets/keys.encrypted"
+
+  age -d -i <(security find-generic-password -w -s swift-repo-private) "$keys_encrypted"
+}
+
+function set_secrets() {
+  if [ "$#" -ne 1 ]; then
+    echo "Illegal number of parameters"
+  else
+    source <(decrypt_secrets) 
+
+    cd "$(project_directory)/$1"
+
+    bundle exec pod keys set devNetworkAuthUsername "$DEV_NETWORK_AUTH_USERNAME"
+    bundle exec pod keys set devNetworkAuthPassword "$DEV_NETWORK_AUTH_PASSWORD"
+    bundle exec pod keys set testNetTestAccountMnemonicsCommaSeparated "$TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED"
+    bundle exec pod keys set dynamicTestAccountFogAuthoritySpki "$DYNAMIC_FOG_AUTHORITY_SPKI"
+    bundle exec pod keys set dynamicTestAccountSeedEntropiesCommaSeparated "$DYNAMIC_TEST_ACCOUNT_SEED_ENTROPIES_COMMA_SEPARATED"
+    bundle exec pod keys set mobileDevTestAccountMnemonicsCommaSeparated "$MOBILEDEV_TEST_ACCOUNT_MNEMONICS_COMMA_SEPERATED"
+  fi
+}
+
+function generate_and_rename_keys() {
+  cd "$(project_directory)/$1"
+
+  bundle exec pod keys generate
+
+  FILE=Pods/CocoaPodsKeys/ExampleKeys.h
+  if test -f "$FILE"; then
+    echo "----------------------------"
+    echo "Keys files generated with INCORRECT name, renaming"
+    echo "----------------------------"
+    set -x
+    find . -name "*ExampleKeys*" | xargs -n 1 -I {} sed -i ''  's/ExampleKeys/MobileCoinKeys/g' {} ;
+    rm Pods/CocoaPodsKeys/MobileCoinKeys* || true; rename 's/Example/MobileCoin/' Pods/CocoaPodsKeys/*
+    set +x
+    echo "----------------------------"
+    echo "Naming substitution complete"
+    echo "----------------------------"
+  else
+    echo "----------------------------"
+    echo "Keys files generated with correct name."
+    echo "----------------------------"
+  fi
+}
+
+function check_for_contributor_public_keys() {
+    echo '----------------------------'
+    echo 'Checking for valid public keys file'
+    echo '----------------------------'
+
+    project_dir=$(project_directory)
+    contributor_public_keys="$project_dir/secrets/contributor_public_keys"
+
+    if [ -s "$contributor_public_keys" ]; then
+      # The file is not-empty.
+      echo '----------------------------'
+      echo "$(wc -l < "$contributor_public_keys") Public keys found"
+      echo '----------------------------'
+    else
+      # The file is empty.
+      echo '----------------------------'
+      echo 'Public keys file not found, or empty, run `generate_and_save_contributor_keys`'
+      echo '----------------------------'
+      exit 1;
+    fi
+}
